from __future__ import annotations

from pathlib import Path

from stock_pipeline.config import PROJECT_ROOT


CRAWLER_SECRET_DIR: Path = PROJECT_ROOT / "local_data" / "secure" / "news_crawler"
BAIDU_PAN_SECRET_DIR: Path = PROJECT_ROOT / "local_data" / "secure" / "baidu_pan"

CREDENTIAL_PUBLIC_FIELDS = {
    "name",
    "source",
    "label",
    "kind",
    "env",
    "description",
    "status_note",
    "status_tone",
    "reloads_next_run",
}

ADMIN_CREDENTIALS = (
    {
        "name": "tushare.api_token",
        "label": "Tushare Token",
        "source": "Tushare",
        "kind": "api_key",
        "storage": "secret_store",
        "env": "TUSHARE_API",
        "description": "Tushare 回退数据源使用的 token。",
        "status_note": "暂停维护",
        "status_tone": "danger",
        "reloads_next_run": True,
    },
    {
        "name": "guardian.api_key",
        "label": "Guardian API Key",
        "source": "Guardian",
        "kind": "api_key",
        "storage": "file",
        "env": "GUARDIAN_API_KEY",
        "file_env": "GUARDIAN_API_KEY_FILE",
        "path": "guardian_api_key.txt",
        "description": "Guardian provider 的 API key。",
        "reloads_next_run": True,
    },
    {
        "name": "guardian.baidu_translate_app_id",
        "label": "Baidu Translate App ID",
        "source": "Baidu Translate",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_TRANSLATE_APP_ID",
        "file_env": "BAIDU_TRANSLATE_APP_ID_FILE",
        "path": "baidu_translate_app_id.txt",
        "description": "百度翻译开放平台的 App ID，用于新闻中文翻译。",
        "reloads_next_run": False,
    },
    {
        "name": "guardian.baidu_translate_secret_key",
        "label": "Baidu Translate Secret Key",
        "source": "Baidu Translate",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_TRANSLATE_SECRET_KEY",
        "file_env": "BAIDU_TRANSLATE_SECRET_KEY_FILE",
        "path": "baidu_translate_secret_key.txt",
        "description": "百度翻译开放平台的密钥，用于新闻中文翻译。",
        "reloads_next_run": False,
    },
    {
        "name": "baidu_pan.app_key",
        "label": "AppKey",
        "source": "Baidu Netdisk",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_PAN_APP_KEY",
        "path": "app_key",
        "secret_dir": "baidu_pan",
        "description": "百度网盘开放平台 AppKey，用于冷数据上传和取回。",
        "reloads_next_run": False,
    },
    {
        "name": "baidu_pan.secret_key",
        "label": "SecretKey",
        "source": "Baidu Netdisk",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_PAN_SECRET_KEY",
        "path": "secret_key",
        "secret_dir": "baidu_pan",
        "description": "百度网盘开放平台 SecretKey。",
        "reloads_next_run": False,
    },
    {
        "name": "baidu_pan.sign_key",
        "label": "SignKey",
        "source": "Baidu Netdisk",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_PAN_SIGN_KEY",
        "path": "sign_key",
        "secret_dir": "baidu_pan",
        "description": "百度网盘开放平台 SignKey。",
        "reloads_next_run": False,
    },
    {
        "name": "baidu_pan.access_token",
        "label": "Access Token",
        "source": "Baidu Netdisk",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_PAN_ACCESS_TOKEN",
        "path": "access_token",
        "secret_dir": "baidu_pan",
        "description": "百度网盘访问令牌，用于 bdpan/API 访问。",
        "reloads_next_run": False,
    },
    {
        "name": "baidu_pan.refresh_token",
        "label": "Refresh Token",
        "source": "Baidu Netdisk",
        "kind": "api_key",
        "storage": "file",
        "env": "BAIDU_PAN_REFRESH_TOKEN",
        "path": "refresh_token",
        "secret_dir": "baidu_pan",
        "description": "百度网盘刷新令牌，用于后续更新 access token。",
        "reloads_next_run": False,
    },
    {
        "name": "bloomberg.cookie",
        "label": "Bloomberg Cookie",
        "source": "Bloomberg",
        "kind": "cookie",
        "storage": "file",
        "env": "BLOOMBERG_COOKIE",
        "file_env": "BLOOMBERG_COOKIE_FILE",
        "path": "bloomberg_cookie.txt",
        "description": "Bloomberg 请求头 Cookie，适合粘贴完整 cookie 字符串。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.cookies_json",
        "label": "Bloomberg Cookies JSON",
        "source": "Bloomberg",
        "kind": "cookie_json",
        "storage": "file",
        "env": "BLOOMBERG_COOKIES_JSON",
        "file_env": "BLOOMBERG_COOKIES_JSON_FILE",
        "path": "bloomberg_cookies_json.txt",
        "description": "Chrome 导出的 Bloomberg cookies JSON 数组，优先用于模拟已登录浏览器会话。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.latest_url",
        "label": "Bloomberg Latest URL",
        "source": "Bloomberg",
        "kind": "url",
        "storage": "file",
        "env": "BLOOMBERG_LATEST_URL",
        "file_env": "BLOOMBERG_LATEST_URL_FILE",
        "path": "bloomberg_latest_url.txt",
        "description": "Bloomberg 最新文章入口页，默认 https://www.bloomberg.com/latest。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.api_url",
        "label": "Bloomberg API URL",
        "source": "Bloomberg",
        "kind": "url",
        "storage": "file",
        "env": "BLOOMBERG_API_URL",
        "file_env": "BLOOMBERG_API_URL_FILE",
        "path": "bloomberg_api_url.txt",
        "description": "Bloomberg lineup-next 文章列表接口，留空则使用默认接口。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.use_api",
        "label": "Bloomberg Use API",
        "source": "Bloomberg",
        "kind": "boolean",
        "storage": "file",
        "env": "BLOOMBERG_USE_API",
        "file_env": "BLOOMBERG_USE_API_FILE",
        "path": "bloomberg_use_api.txt",
        "description": "是否优先使用 Bloomberg API 发现文章，填 1/0 或 true/false。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.require_login_cookie",
        "label": "Bloomberg Require Login Cookie",
        "source": "Bloomberg",
        "kind": "boolean",
        "storage": "file",
        "env": "BLOOMBERG_REQUIRE_LOGIN_COOKIE",
        "file_env": "BLOOMBERG_REQUIRE_LOGIN_COOKIE_FILE",
        "path": "bloomberg_require_login_cookie.txt",
        "description": "启用后会检查 _breg-uid 等关键登录 cookie，不完整则直接停止。",
        "reloads_next_run": True,
    },
    {
        "name": "bloomberg.proxy",
        "label": "Bloomberg Proxy",
        "source": "Bloomberg",
        "kind": "proxy",
        "storage": "file",
        "env": "BLOOMBERG_PROXY",
        "file_env": "BLOOMBERG_PROXY_FILE",
        "path": "bloomberg_proxy.txt",
        "description": "Bloomberg 出站代理，例如 http://user:pass@host:port。",
        "reloads_next_run": True,
    },
    {
        "name": "politico_browser.proxy",
        "label": "Politico Browser Proxy",
        "source": "Politico",
        "kind": "proxy",
        "storage": "file",
        "env": "POLITICO_BROWSER_PROXY",
        "file_env": "POLITICO_BROWSER_PROXY_FILE",
        "path": "politico_browser_proxy.txt",
        "description": "Politico 浏览器 provider 使用的代理。",
        "reloads_next_run": True,
    },
    {
        "name": "politico_browser.cookies_json",
        "label": "Politico Cookies JSON",
        "source": "Politico",
        "kind": "cookie_json",
        "storage": "file",
        "env": "POLITICO_BROWSER_COOKIES_JSON",
        "file_env": "POLITICO_BROWSER_COOKIES_JSON_FILE",
        "path": "politico_browser_cookies_json.txt",
        "description": "Playwright cookies JSON 数组，用于复用已验证会话。",
        "reloads_next_run": True,
    },
)
