from __future__ import annotations

from typing import Any


DATASET_LABELS = {
    "stock_basic": "股票基础信息",
    "namechange": "股票曾用名",
    "stock_company": "上市公司信息",
    "stk_managers": "管理层信息",
    "stk_rewards": "管理层薪酬持股",
    "daily": "日线行情",
    "weekly": "周线行情",
    "monthly": "月线行情",
    "daily_basic": "每日估值指标",
    "adj_factor": "复权因子",
    "stk_limit": "涨跌停价格",
    "suspend_d": "停复牌信息",
    "moneyflow": "个股资金流向",
    "margin_detail": "融资融券明细",
    "income": "利润表",
    "balancesheet": "资产负债表",
    "cashflow": "现金流量表",
    "fina_indicator": "财务指标",
    "express": "业绩快报",
    "forecast": "业绩预告",
    "dividend": "分红送股",
    "fina_mainbz": "主营业务构成",
    "fina_audit": "财务审计意见",
    "disclosure_date": "财报披露计划",
    "top10_holders": "十大股东",
    "top10_floatholders": "十大流通股东",
    "stk_holdernumber": "股东户数",
    "stk_holdertrade": "股东增减持",
    "pledge_stat": "股权质押统计",
    "pledge_detail": "股权质押明细",
    "repurchase": "股票回购",
    "share_float": "限售解禁",
    "block_trade": "大宗交易",
    "index_member_all": "申万行业归属",
    "sw_daily": "申万行业日行情",
    "anns_d": "公司公告",
    "tdx_intraday_minutes": "通达信分钟 K 线",
    "pytdx_history_minutes": "pytdx 历史分钟价量",
    "ths_intraday_minutes": "同花顺分钟分时行情",
}


FIELD_LABELS = {
    "ts_code": "股票代码",
    "symbol": "股票简称代码",
    "name": "名称",
    "fullname": "公司全称",
    "enname": "英文名称",
    "area": "地区",
    "industry": "所属行业",
    "market": "市场类型",
    "exchange": "交易所",
    "list_date": "上市日期",
    "list_status": "上市状态",
    "act_name": "实际控制人",
    "act_ent_type": "实控人类型",
    "start_date": "开始日期",
    "end_date": "截止日期",
    "ann_date": "公告日期",
    "f_ann_date": "实际公告日期",
    "change_reason": "变更原因",
    "com_name": "公司名称",
    "com_id": "统一社会信用代码",
    "chairman": "董事长",
    "manager": "总经理",
    "secretary": "董秘",
    "reg_capital": "注册资本",
    "setup_date": "成立日期",
    "province": "省份",
    "city": "城市",
    "introduction": "公司介绍",
    "website": "官网",
    "email": "邮箱",
    "office": "办公地址",
    "employees": "员工人数",
    "main_business": "主营业务",
    "business_scope": "经营范围",
    "gender": "性别",
    "lev": "职务层级",
    "title": "职务",
    "edu": "学历",
    "national": "国籍",
    "birthday": "出生年月",
    "begin_date": "任职开始日期",
    "reward": "报酬",
    "hold_vol": "持股数量",
    "trade_date": "交易日期",
    "minute": "分钟",
    "datetime": "时间",
    "price": "价格",
    "amount": "成交额",
    "amount_estimated": "成交额估算",
    "ohlc_estimated": "OHLC估算",
    "avg_price": "均价",
    "volume": "成交量",
    "pre_close": "昨收",
    "source": "来源",
    "dataset": "数据集",
    "market_code": "行情代码",
    "market_type": "市场类型",
    "fetched_at": "抓取时间",
    "open": "开盘价",
    "high": "最高价",
    "low": "最低价",
    "close": "收盘价",
    "pre_close": "昨收价",
    "change": "涨跌额",
    "pct_chg": "涨跌幅",
    "pct_change": "涨跌幅",
    "vol": "成交量",
    "amount": "成交额",
    "turnover_rate": "换手率",
    "turnover_rate_f": "自由流通换手率",
    "volume_ratio": "量比",
    "pe": "市盈率",
    "pe_ttm": "滚动市盈率",
    "pb": "市净率",
    "ps": "市销率",
    "ps_ttm": "滚动市销率",
    "dv_ratio": "股息率",
    "dv_ttm": "滚动股息率",
    "total_share": "总股本",
    "float_share": "流通股本",
    "free_share": "自由流通股本",
    "total_mv": "总市值",
    "circ_mv": "流通市值",
    "adj_factor": "复权因子",
    "up_limit": "涨停价",
    "down_limit": "跌停价",
    "buy_sm_vol": "小单买入量",
    "buy_sm_amount": "小单买入额",
    "sell_sm_vol": "小单卖出量",
    "sell_sm_amount": "小单卖出额",
    "buy_md_vol": "中单买入量",
    "buy_md_amount": "中单买入额",
    "sell_md_vol": "中单卖出量",
    "sell_md_amount": "中单卖出额",
    "buy_lg_vol": "大单买入量",
    "buy_lg_amount": "大单买入额",
    "sell_lg_vol": "大单卖出量",
    "sell_lg_amount": "大单卖出额",
    "buy_elg_vol": "特大单买入量",
    "buy_elg_amount": "特大单买入额",
    "sell_elg_vol": "特大单卖出量",
    "sell_elg_amount": "特大单卖出额",
    "net_mf_vol": "净流入量",
    "net_mf_amount": "净流入额",
    "rzye": "融资余额",
    "rqye": "融券余额",
    "rzmre": "融资买入额",
    "rqyl": "融券余量",
    "rzche": "融资偿还额",
    "rqchl": "融券偿还量",
    "rqmcl": "融券卖出量",
    "rzrqye": "融资融券余额",
    "report_type": "报告类型",
    "comp_type": "公司类型",
    "end_type": "报告期类型",
    "basic_eps": "基本每股收益",
    "diluted_eps": "稀释每股收益",
    "total_revenue": "营业总收入",
    "revenue": "营业收入",
    "operate_profit": "营业利润",
    "total_profit": "利润总额",
    "income_tax": "所得税",
    "n_income": "净利润",
    "n_income_attr_p": "归母净利润",
    "minority_gain": "少数股东损益",
    "ebit": "息税前利润",
    "ebitda": "息税折旧摊销前利润",
    "total_cogs": "营业总成本",
    "oper_cost": "营业成本",
    "sell_exp": "销售费用",
    "admin_exp": "管理费用",
    "fin_exp": "财务费用",
    "rd_exp": "研发费用",
    "invest_income": "投资收益",
    "assets_impair_loss": "资产减值损失",
    "total_assets": "资产总计",
    "total_liab": "负债合计",
    "total_hldr_eqy_exc_min_int": "归母股东权益",
    "money_cap": "货币资金",
    "accounts_receiv": "应收账款",
    "inventories": "存货",
    "total_cur_assets": "流动资产合计",
    "total_nca": "非流动资产合计",
    "total_cur_liab": "流动负债合计",
    "total_ncl": "非流动负债合计",
    "fix_assets": "固定资产",
    "goodwill": "商誉",
    "intan_assets": "无形资产",
    "st_borr": "短期借款",
    "lt_borr": "长期借款",
    "bond_payable": "应付债券",
    "net_profit": "净利润",
    "n_cashflow_act": "经营活动现金流量净额",
    "n_cashflow_inv_act": "投资活动现金流量净额",
    "n_cash_flows_fnc_act": "筹资活动现金流量净额",
    "free_cashflow": "自由现金流",
    "c_cash_equ_beg_period": "期初现金及等价物余额",
    "c_cash_equ_end_period": "期末现金及等价物余额",
    "update_flag": "更新标识",
    "eps": "每股收益",
    "dt_eps": "稀释每股收益",
    "total_revenue_ps": "每股营业总收入",
    "revenue_ps": "每股营业收入",
    "capital_rese_ps": "每股资本公积",
    "surplus_rese_ps": "每股盈余公积",
    "undist_profit_ps": "每股未分配利润",
    "profit_dedt": "扣非净利润",
    "gross_margin": "毛利",
    "grossprofit_margin": "毛利率",
    "netprofit_margin": "净利率",
    "current_ratio": "流动比率",
    "quick_ratio": "速动比率",
    "cash_ratio": "现金比率",
    "ar_turn": "应收账款周转率",
    "ca_turn": "流动资产周转率",
    "fa_turn": "固定资产周转率",
    "assets_turn": "总资产周转率",
    "fcff": "企业自由现金流",
    "fcfe": "股权自由现金流",
    "bps": "每股净资产",
    "ocfps": "每股经营现金流",
    "cfps": "每股现金流",
    "roe": "净资产收益率",
    "roe_waa": "加权净资产收益率",
    "roe_dt": "扣非净资产收益率",
    "roa": "总资产收益率",
    "roic": "投入资本回报率",
    "debt_to_assets": "资产负债率",
    "assets_to_eqt": "权益乘数",
    "or_yoy": "营业收入同比增长",
    "op_yoy": "营业利润同比增长",
    "netprofit_yoy": "净利润同比增长",
    "dt_netprofit_yoy": "扣非净利润同比增长",
    "ocf_yoy": "经营现金流同比增长",
    "type": "预告类型",
    "p_change_min": "净利润变动下限",
    "p_change_max": "净利润变动上限",
    "net_profit_min": "预计净利润下限",
    "net_profit_max": "预计净利润上限",
    "last_parent_net": "上年同期归母净利润",
    "first_ann_date": "首次公告日期",
    "summary": "摘要",
    "div_proc": "分红进度",
    "stk_div": "每股送转",
    "stk_bo_rate": "送股比例",
    "stk_co_rate": "转增比例",
    "cash_div": "每股现金分红",
    "cash_div_tax": "税后现金分红",
    "record_date": "股权登记日",
    "ex_date": "除权除息日",
    "pay_date": "派息日",
    "div_listdate": "红股上市日",
    "imp_ann_date": "实施公告日",
    "bz_item": "业务项目",
    "bz_code": "业务代码",
    "bz_sales": "主营收入",
    "bz_profit": "主营利润",
    "bz_cost": "主营成本",
    "curr_type": "货币类型",
    "audit_result": "审计意见",
    "audit_fees": "审计费用",
    "audit_agency": "会计师事务所",
    "audit_sign": "签字会计师",
    "holder_name": "股东名称",
    "hold_amount": "持股数量",
    "hold_ratio": "持股比例",
    "hold_float_ratio": "流通持股比例",
    "hold_change": "持股变动",
    "holder_type": "股东类型",
    "holder_num": "股东户数",
    "in_de": "增减持方向",
    "change_vol": "变动数量",
    "change_ratio": "变动比例",
    "after_share": "变动后持股",
    "after_ratio": "变动后持股比例",
    "avg_price": "成交均价",
    "pledge_count": "质押次数",
    "unrest_pledge": "无限售质押股数",
    "rest_pledge": "限售质押股数",
    "pledge_ratio": "质押比例",
    "pledge_amount": "质押数量",
    "is_release": "是否解押",
    "release_date": "解押日期",
    "pledgor": "质权人",
    "holding_amount": "持股总数",
    "pledged_amount": "累计质押数量",
    "p_total_ratio": "占总股本比例",
    "h_total_ratio": "占持股比例",
    "is_buyback": "是否回购质押",
    "float_date": "解禁日期",
    "float_ratio": "解禁比例",
    "share_type": "股份类型",
    "price": "成交价格",
    "buyer": "买方营业部",
    "seller": "卖方营业部",
    "l1_code": "一级行业代码",
    "l1_name": "一级行业名称",
    "l2_code": "二级行业代码",
    "l2_name": "二级行业名称",
    "l3_code": "三级行业代码",
    "l3_name": "三级行业名称",
    "in_date": "纳入日期",
    "out_date": "剔除日期",
    "is_new": "是否最新",
    "url": "链接",
}


TOKEN_LABELS = {
    "n": "净",
    "net": "净",
    "total": "总",
    "stot": "总",
    "c": "现金",
    "cash": "现金",
    "flow": "流",
    "flows": "流",
    "asset": "资产",
    "assets": "资产",
    "liab": "负债",
    "liability": "负债",
    "cur": "流动",
    "noncur": "非流动",
    "noncurrent": "非流动",
    "revenue": "收入",
    "income": "收益",
    "profit": "利润",
    "cost": "成本",
    "exp": "费用",
    "tax": "税",
    "inv": "投资",
    "act": "活动",
    "oper": "经营",
    "operate": "经营",
    "fnc": "筹资",
    "fin": "财务",
    "sale": "销售",
    "sales": "销售",
    "admin": "管理",
    "int": "利息",
    "loan": "贷款",
    "loans": "贷款",
    "debt": "债务",
    "eqt": "权益",
    "share": "股份",
    "shares": "股份",
    "ratio": "比例",
    "rate": "比例",
    "amount": "金额",
    "vol": "数量",
    "date": "日期",
    "beg": "期初",
    "end": "期末",
    "period": "期间",
    "yoy": "同比",
    "q": "季度",
    "eps": "每股收益",
    "ps": "每股",
    "ttm": "滚动",
    "margin": "率",
    "turn": "周转率",
    "holder": "股东",
    "pledge": "质押",
    "div": "分红",
    "ann": "公告",
}


def dataset_label(api_name: str) -> str:
    return DATASET_LABELS.get(api_name, api_name)


def field_label(field: str) -> str:
    if field in FIELD_LABELS:
        return FIELD_LABELS[field]
    parts = [TOKEN_LABELS.get(part, "") for part in field.split("_")]
    text = "".join(part for part in parts if part)
    return text or field


def dataset_columns(records: list[dict[str, Any]]) -> list[dict[str, str]]:
    fields: list[str] = []
    for row in records:
        for key in row.keys():
            if key not in fields:
                fields.append(key)
    return [{"key": key, "label": field_label(key)} for key in fields]


def build_table_datasets(datasets: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    items = []
    for key, records in datasets.items():
        items.append(
            {
                "key": key,
                "label": dataset_label(key),
                "row_count": len(records),
                "columns": dataset_columns(records),
                "records": records,
            }
        )
    return sorted(items, key=lambda item: (item["row_count"] == 0, item["label"]))
