from __future__ import annotations

try:
    from pypinyin import Style, lazy_pinyin  # type: ignore
except ImportError:  # pragma: no cover - optional dependency
    Style = None
    lazy_pinyin = None


PINYIN_OVERRIDES = {
    "牧": "mu",
    "原": "yuan",
    "股": "gu",
    "份": "fen",
    "平": "ping",
    "安": "an",
    "银": "yin",
    "行": "hang",
    "贵": "gui",
    "州": "zhou",
    "茅": "mao",
    "台": "tai",
    "宁": "ning",
    "德": "de",
    "时": "shi",
    "代": "dai",
    "中": "zhong",
    "国": "guo",
    "石": "shi",
    "油": "you",
    "化": "hua",
    "工": "gong",
    "商": "shang",
    "建": "jian",
    "设": "she",
    "农": "nong",
    "业": "ye",
    "招": "zhao",
    "浦": "pu",
    "发": "fa",
    "兴": "xing",
    "民": "min",
    "生": "sheng",
    "光": "guang",
    "大": "da",
    "华": "hua",
    "夏": "xia",
    "江": "jiang",
    "苏": "su",
    "浙": "zhe",
    "温": "wen",
    "都": "du",
    "宇": "yu",
    "通": "tong",
    "客": "ke",
    "车": "che",
    "比": "bi",
    "亚": "ya",
    "迪": "di",
    "长": "chang",
    "城": "cheng",
    "汽": "qi",
    "五": "wu",
    "粮": "liang",
    "液": "ye",
    "泸": "lu",
    "老": "lao",
    "窖": "jiao",
    "伊": "yi",
    "利": "li",
    "海": "hai",
    "天": "tian",
    "味": "wei",
    "科": "ke",
    "技": "ji",
    "讯": "xun",
    "飞": "fei",
    "恒": "heng",
    "瑞": "rui",
    "医": "yi",
    "药": "yao",
    "迈": "mai",
    "阿": "a",
    "里": "li",
    "腾": "teng",
    "富": "fu",
    "士": "shi",
    "康": "kang",
    "立": "li",
    "讯": "xun",
    "精": "jing",
    "密": "mi",
    "东": "dong",
    "方": "fang",
    "财": "cai",
    "同": "tong",
    "花": "hua",
    "顺": "shun",
    "京": "jing",
    "沪": "hu",
    "高": "gao",
    "铁": "tie",
    "航": "hang",
    "空": "kong",
    "南": "nan",
    "北": "bei",
    "方": "fang",
    "稀": "xi",
    "土": "tu",
    "洛": "luo",
    "阳": "yang",
    "钼": "mu",
    "紫": "zi",
    "金": "jin",
    "矿": "kuang",
    "赣": "gan",
    "锋": "feng",
    "锂": "li",
    "盐": "yan",
    "湖": "hu",
    "新": "xin",
    "能": "neng",
    "源": "yuan",
    "正": "zheng",
    "泰": "tai",
    "隆": "long",
    "基": "ji",
    "绿": "lv",
    "阳": "yang",
    "爱": "ai",
    "旭": "xu",
    "晶": "jing",
    "澳": "ao",
    "特": "te",
    "变": "bian",
    "电": "dian",
    "福": "fu",
    "耀": "yao",
    "玻": "bo",
    "璃": "li",
    "格": "ge",
    "力": "li",
    "美": "mei",
    "的": "di",
    "集": "ji",
    "团": "tuan",
    "海": "hai",
    "尔": "er",
    "智": "zhi",
    "家": "jia",
    "三": "san",
    "一": "yi",
    "重": "zhong",
    "徐": "xu",
    "徐": "xu",
    "机": "ji",
    "械": "xie",
    "广": "guang",
    "联": "lian",
    "达": "da",
    "宝": "bao",
    "钢": "gang",
    "武": "wu",
    "鞍": "an",
    "包": "bao",
    "山": "shan",
    "西": "xi",
    "汾": "fen",
    "酒": "jiu",
    "古": "gu",
    "井": "jing",
    "贡": "gong",
    "片": "pian",
    "仔": "zi",
    "癀": "huang",
    "云": "yun",
    "白": "bai",
    "云南": "yunnan",
}


def pinyin_tokens(text: str) -> tuple[str, str]:
    if lazy_pinyin and Style:
        full = lazy_pinyin(text, style=Style.NORMAL, errors="ignore")
        initials = lazy_pinyin(text, style=Style.FIRST_LETTER, errors="ignore")
        return "".join(full).lower(), "".join(initials).lower()

    parts = []
    initials = []
    for char in text:
        token = PINYIN_OVERRIDES.get(char)
        if token:
            parts.append(token)
            initials.append(token[0])
        elif char.isascii() and char.isalnum():
            parts.append(char.lower())
            initials.append(char.lower()[0])
    return "".join(parts), "".join(initials)
