from __future__ import annotations

from typing import Any, Protocol

from .dedupe import DedupeKeys
from .models import CrawlResult, NewsArticle


class NewsRepository(Protocol):
    def ensure_indexes(self) -> None: ...
    def find_existing_by_keys(self, keys: DedupeKeys) -> dict[str, Any] | None: ...
    def upsert_article(self, article: NewsArticle, keys: DedupeKeys) -> str: ...
    def close(self) -> None: ...


class CrawlRunRepository(Protocol):
    def start(self, result: CrawlResult) -> None: ...
    def finish(self, result: CrawlResult) -> None: ...
    def request_cancel(self, run_id: str) -> bool: ...
    def is_cancel_requested(self, run_id: str) -> bool: ...
    def recent_runs(self, source_name: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    def update_health(self, source_name: str) -> dict[str, Any]: ...
    def pause_source(self, source_name: str, reason: str, *, run_id: str = "", issue_code: str = "") -> None: ...
    def active_pauses(self) -> list[dict[str, Any]]: ...


class CheckpointRepository(Protocol):
    def save_checkpoint(self, source_name: str, key: str, value: dict[str, Any]) -> None: ...
    def load_checkpoint(self, source_name: str, key: str) -> dict[str, Any] | None: ...
